spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/EC
    username: postgres
    password: postgres
  jmx:
    default-domain: ec-202404c
server:
  servlet:
    context-path: /ec-202404c

credit-card-check-api: http://153.127.48.168:8080/sample-credit-card-web-api/credit-card/payment