spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/EC
    username: postgres
    password: postgres
  jmx:
    default-domain: ec-202404c
server:
  servlet:
    context-path: /ec-202404c
  mail:
    host: smtp.gmail.com
    port: 587
    username: ymnk10ymnk10@gmail.com
    password: mijevhvvxccpinwk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

credit-card-check-api: http://153.127.48.168:8080/sample-credit-card-web-api/credit-card/payment